INSERT INTO emotion (code, name, name_en, description, color) VALUES
('JOY', 'Joie', 'Joy', 'Sentiment de bonheur, d’allégresse, de gratitude', '#FFD700'),
('PEACE', 'Paix', 'Peace', 'Calme intérieur, sérénité, absence de trouble', '#87CEEB'),
('TRUST', 'Confiance', 'Trust', 'Assurance, foi, sentiment de sécurité', '#4682B4'),
('HOPE', 'Espérance', 'Hope', 'Attente positive, confiance en l’avenir', '#90EE90'),
('LOVE', 'Amour', 'Love', 'Affection, charité, bienveillance', '#FF69B4'),
('GRATITUDE', 'Reconnaissance', 'Gratitude', 'Remerciement, appréciation', '#FFA500'),
('ADMIRATION', 'Admiration', 'Admiration', 'Respect, émerveillement', '#8A2BE2'),
('FEAR', 'Peur', 'Fear', 'Crainte, inquiétude, angoisse', '#A9A9A9'),
('SADNESS', 'Tristesse', 'Sadness', 'Chagrin, peine, mélancolie', '#1E90FF'),
('ANGER', 'Colère', 'Anger', 'Irritation, indignation, frustration', '#DC143C'),
('DISGUST', 'Dégoût', 'Disgust', 'Répulsion, rejet', '#228B22'),
('SURPRISE', 'Surprise', 'Surprise', 'Étonnement, choc, émerveillement', '#FFDAB9'),
('GUILT', 'Culpabilité', 'Guilt', 'Remords, regret, sentiment de faute', '#B22222'),
('SHAME', 'Honte', 'Shame', 'Malaise, embarras, humiliation', '#D2691E'),
('COMPASSION', 'Compassion', 'Compassion', 'Empathie, pitié, sollicitude', '#FFB6C1'),
('ZEAL', 'Zèle', 'Zeal', 'Enthousiasme, ardeur, ferveur', '#FF8C00'),
('REVERENCE', 'Crainte de Dieu', 'Reverence', 'Respect sacré, adoration, humilité', '#2E8B57'),
('DOUBT', 'Doute', 'Doubt', 'Incertitude, questionnement', '#808080'),
('LONELINESS', 'Solitude', 'Loneliness', 'Isolement, sentiment d’abandon', '#708090'),
('RELIEF', 'Soulagement', 'Relief', 'Fin d’une épreuve, apaisement', '#F0E68C');
